language: node_js
node_js:
- '10'
cache: yarn
script:
- yarn test
before_install:
- openssl aes-256-cbc -K $encrypted_1776d78c0fa5_key -iv $encrypted_1776d78c0fa5_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
