language: node_js

node_js:
  - '10'
cache: yarn

script:
  - yarn test

addons:
    ssh_known_hosts: 
    - 111.231.197.67

before_install:
  - openssl aes-256-cbc -K $encrypted_1776d78c0fa5_key -iv $encrypted_1776d78c0fa5_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d

after_success:
  - chmod 600 ~/.ssh/id_rsa
  - ssh travis@111.231.197.67 StrictHostKeyChecking=no 'cd ~ && git clone https://github.com/bushuai/x.git xxx'